import { useEffect, useMemo, useRef, useState } from "react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { AspectRatioGuide, BuildingScoringGuide, GreenCoverGuide, WindVentilationGuide } from "@/components/Guides";
import { Page } from "@/components/FieldworkShell";
import { buildingCriteria, envOptions, environmentItems, goods, scoreHints, shopTypes, socialItems, type ZoneId } from "@/data/fieldwork";
import { zoneBackgroundStyle } from "@/lib/submissionDisplay";
import { useLanguage } from "@/i18n/LanguageContext";
import { hasLocalDraft, loadLocal, saveLocal, submitData } from "@/lib/fieldworkApi";
import type { TranslationKey } from "@/i18n/translations";

function useZoneTask(){ const p=useParams(); return { zone:(p.zoneId||"A") as ZoneId, task:p.taskId||"building"}; }
function useIsReview(){ const loc=useLocation(); return new URLSearchParams(loc.search).get("review")==="true"; }
function useIsEdit(){ const loc=useLocation(); return new URLSearchParams(loc.search).get("edit")==="true"; }
function grade(total:number){ if(total<=9)return "severe"; if(total<=17)return "poor"; if(total<=26)return "good"; return "excellent"; }
function moneyIndex(v:number){ if(v>=30&&v<=49)return 10; if(v<=89)return 7; if(v<=149)return 4; return 1; }
function markSubmitted(zone:ZoneId,task:string){ const completed=JSON.parse(localStorage.getItem("fieldwork_completed")||"{}"); completed[`${zone}_${task}`]=true; localStorage.setItem("fieldwork_completed",JSON.stringify(completed)); localStorage.setItem(`fieldwork_zone_${zone}_${task}_submitted`,"true"); window.dispatchEvent(new Event("fieldwork-submitted")); }

type DraftStatus = "idle" | "restored" | "saving" | "saved" | "pending" | "error";
function useDraftState<T>(zone: ZoneId, task: string, fallback: T) {
  const [data, setData] = useState<T>(() => loadLocal(zone, task, fallback));
  const [status, setStatus] = useState<DraftStatus>(() => hasLocalDraft(zone, task) ? "restored" : "idle");
  const first = useRef(true);
  useEffect(() => {
    if (first.current) { first.current = false; return; }
    setStatus("saving");
    const timer = window.setTimeout(() => {
      try { saveLocal(zone, task, data); setStatus("saved"); }
      catch { setStatus("error"); }
    }, 650);
    return () => window.clearTimeout(timer);
  }, [data, task, zone]);
  return { data, setData, status, setStatus };
}
function AutosaveBadge({status}:{status:DraftStatus}){const{t}=useLanguage();if(status==="idle")return <div role="status" aria-live="polite" className="mb-3 rounded-2xl border border-slate-200 bg-white/80 px-3 py-2 text-sm font-semibold text-muted-foreground">{t("autosaveIdle")}</div>;const style=status==="error"?"border-red-200 bg-red-50 text-red-700":status==="saving"||status==="pending"?"border-amber-200 bg-amber-50 text-amber-800":"border-green-200 bg-green-50 text-green-700";return <div role="status" aria-live="polite" className={`mb-3 rounded-2xl border px-3 py-2 text-sm font-semibold ${style}`}>{t((`autosave${status[0].toUpperCase()}${status.slice(1)}`) as TranslationKey)}</div>;}
async function submitWithDraft(zone: ZoneId, task: string, payload: unknown, rawData: unknown, setStatus: (status: DraftStatus) => void) { try { saveLocal(zone, task, rawData); } catch { /* Do not block a valid server submission when local storage is unavailable. */ } try { const result = await submitData(zone, task, payload); markSubmitted(zone, task); setStatus("saved"); return result; } catch (error) { try { saveLocal(zone, task, rawData); } catch { /* best-effort retry draft */ } setStatus("pending"); throw error; } }
function submitErrorMessage(error: unknown, lang: "zh" | "en") { const detail = error instanceof Error ? error.message : ""; if (detail.includes("endpoint") || detail.includes("Apps Script")) return lang === "zh" ? "未連接 Google Sheet。請先把 Apps Script Web App 的 /exec URL 填入 app-config.js；草稿已保留。" : "Google Sheet is not connected. Add the Apps Script Web App /exec URL to app-config.js; the draft has been kept."; return lang === "zh" ? "提交失敗。草稿已保留，請稍後重試。" : "Submission failed. The draft has been kept for retry."; }
function SubmitErrorAlert({message}:{message:string}){if(!message)return null;return <div role="alert" className="mt-4 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold leading-6 text-red-700">{message}</div>;}

function GradeBadge({label}:{label:string}){const map:Record<string,string>={severe:"bg-red-100 text-red-700",poor:"bg-amber-100 text-amber-800",good:"bg-cyan-100 text-cyan-800",excellent:"bg-blue-100 text-blue-800"};return <span className={`inline-block rounded-full px-3 py-1 text-xs font-bold ${map[label]??"bg-gray-100"}`}>{label}</span>;}
function SubmittedBanner({onBack}:{onBack:()=>void}){const{t}=useLanguage();return <div className="mt-4 rounded-2xl border-2 border-green-400 bg-green-50 p-4 text-center"><p className="text-xl font-black text-green-700">{t("submittedBanner")}</p><button type="button" className="secondary-btn mt-3" onClick={onBack}>{t("back")}</button></div>;}
function SubmitBar({onSubmit,loading}:{onSubmit:()=>void;loading?:boolean}){const{t}=useLanguage();const nav=useNavigate();const isEdit=useIsEdit();return <div className="mt-4 flex gap-2"><button type="button" className="secondary-btn min-h-[44px] flex-1" onClick={()=>nav(-1)}>{t("back")}</button><button type="button" onClick={onSubmit} disabled={loading} className="primary-btn min-h-[44px] flex-1">{loading?"…":t(isEdit?"updateSubmission":"submit")}</button></div>;}

function IndicatorCard({text,children}:{text:string;children?:React.ReactNode}){const{t}=useLanguage();return <section className="field-card border-primary/30 bg-primary/5"><h2 className="text-lg font-black text-primary">{t("scoringIndicators")}</h2><p className="mt-2 text-sm leading-6">{text}</p>{children}</section>;}

export function BuildingScoringForm(){
  const{t,lang}=useLanguage();const{zone}=useZoneTask();const isReview=useIsReview();
  const fallback=useMemo(()=>Array.from({length:5},()=>Object.fromEntries(buildingCriteria.map(k=>[k,0]))as Record<string,number>),[]);const{data,setData,status,setStatus}=useDraftState(zone,"building",fallback);const[submitted,setSubmitted]=useState(isReview);const[loading,setLoading]=useState(false);const[submitError,setSubmitError]=useState("");const totals=data.map(b=>Object.values(b).reduce((a,n)=>a+Number(n),0));const avg=totals.reduce((a,n)=>a+n,0)/5;const nav=useNavigate();
  async function submit(){setLoading(true);setSubmitError("");try{await submitWithDraft(zone,"building",{buildings:data,totals,average:avg},data,setStatus);setSubmitted(true);}catch(err){setSubmitError(submitErrorMessage(err,lang));}finally{setLoading(false);}}
  if(submitted)return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<h1 className="text-2xl font-black text-primary">{t("reviewTitle")}</h1><SubmittedBanner onBack={()=>nav(`/zone/${zone}?tab=tasks`, { replace: true })}/><div className="mt-4 space-y-3">{data.map((b,i)=><div className="field-card" key={i}><h2 className="font-bold">{t("building")} {i+1} · {t("total")}: {totals[i]}/35 · <GradeBadge label={t(grade(totals[i])as any)}/></h2>{buildingCriteria.map(k=><div key={k} className="mt-2 flex justify-between text-sm"><span>{t(k)}</span><b>{b[k]}/5</b></div>)}</div>)}<div className="field-card"><b>{t("buildingAvg")}: {avg.toFixed(1)}/35 · {t(grade(avg)as any)}</b></div></div></Page>;
  return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<AutosaveBadge status={status}/><BuildingScoringGuide/><IndicatorCard text={t("buildingGuide")}><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4">{[["0–9","severe"],["10–17","poor"],["18–26","good"],["27–35","excellent"]].map(([r,g])=><div key={g} className="rounded-xl bg-white p-2 text-center"><b>{r}</b><span className="block">{t(g as any)}</span></div>)}</div></IndicatorCard><form className="mt-4 space-y-4">{data.map((b,i)=><div className="field-card" key={i}><h2 className="font-bold">{t("building")} {i+1} · {t("total")} {totals[i]} · {t(grade(totals[i])as any)}</h2>{buildingCriteria.map(k=><label key={k} className="mt-4 block"><span className="font-semibold">{t(k)}</span><input aria-label={`${t(k)} ${t("score")}`} type="range" min="0" max="5" value={b[k]} onChange={e=>{const copy=[...data];copy[i]={...copy[i],[k]:Number(e.target.value)};setData(copy)}} className="min-h-[44px] w-full accent-primary"/><p className="mb-2 text-sm font-bold text-primary">{b[k]}/5</p><div className="grid gap-2 sm:grid-cols-3">{scoreHints[k]?.map(h=><div key={h.range} className="rounded-xl border bg-muted/40 p-2 text-xs"><b>{h.range}</b><span className="mt-1 block leading-5">{lang==="zh"?h.zh:h.en}</span></div>)}</div></label>)}</div>)}</form><div className="field-card mt-4"><b>{t("average")}: {avg.toFixed(1)} / 35</b></div><SubmitErrorAlert message={submitError}/><SubmitBar onSubmit={submit} loading={loading}/></Page>;
}

export function EnvironmentForm(){
  const{t,lang}=useLanguage();const{zone}=useZoneTask();const isReview=useIsReview();const fallback=useMemo(()=>Object.fromEntries(environmentItems.map(k=>[k,0])) as Record<string,number>,[]);const{data,setData,status,setStatus}=useDraftState(zone,"environment",fallback);const[submitted,setSubmitted]=useState(isReview);const[loading,setLoading]=useState(false);const[submitError,setSubmitError]=useState("");const total=Object.values(data).reduce((a,n)=>a+n,0);const nav=useNavigate();async function submit(){setLoading(true);setSubmitError("");try{await submitWithDraft(zone,"environment",{scores:data,total,average:total/6},data,setStatus);setSubmitted(true);}catch(err){setSubmitError(submitErrorMessage(err,lang));}finally{setLoading(false);}}
  if(submitted)return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<h1 className="text-2xl font-black text-primary">{t("reviewTitle")}</h1><SubmittedBanner onBack={()=>nav(`/zone/${zone}?tab=tasks`, { replace: true })}/><div className="mt-4 space-y-3">{environmentItems.map(k=><div className="field-card flex items-center justify-between" key={k}><b>{t(k)}</b><span className="font-mono font-bold text-primary">{data[k]}/10</span></div>)}<div className="field-card"><b>{t("total")}: {total}/60 · {t("average")}: {(total/6).toFixed(1)}/10</b></div></div></Page>;
  return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<AutosaveBadge status={status}/><AspectRatioGuide/><WindVentilationGuide/><GreenCoverGuide/><IndicatorCard text={lang==="zh"?"沿途仔細觀察及測量，按工作紙準則選擇最吻合的描述：最高10分、高7分、中等4分、最低0分。":"Observe and measure carefully along the route. Choose the closest worksheet description: highest sustainability 10, high 7, medium 4, lowest 0."}><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4">{["10","7","4","0"].map(s=><div key={s} className="rounded-xl bg-white p-2 text-center"><b>{s}</b><span className="block">{t("points")}</span></div>)}</div></IndicatorCard><div className="mt-4 space-y-3">{environmentItems.map(k=><div className="field-card" key={k}><b>{t(k)}</b><div className="mt-2 grid gap-2 sm:grid-cols-2">{envOptions[k].map(o=><button type="button" className={`${data[k]===o.score?"primary-btn":"secondary-btn"} min-h-[56px] text-left`} key={`${o.score}-${o.labelEn}`} onClick={()=>setData({...data,[k]:o.score})}><span>{lang==="zh"?o.labelZh:o.labelEn}</span><b className="ml-2">· {o.score} {t("points")}</b></button>)}</div></div>)}</div><div className="field-card mt-4"><b>{t("total")}: {total}/60 · {t("average")}: {(total/6).toFixed(1)}/10</b></div><SubmitErrorAlert message={submitError}/><SubmitBar onSubmit={submit} loading={loading}/></Page>;
}

export function SocialCulturalForm(){
  const{t,lang}=useLanguage();const{zone}=useZoneTask();const isReview=useIsReview();const fallback=useMemo(()=>Object.fromEntries(socialItems.map(k=>[k,{count:0,description:""}])) as Record<string,{count:number;description:string}>,[]);const{data,setData,status,setStatus}=useDraftState(zone,"social-cultural",fallback);const[submitted,setSubmitted]=useState(isReview);const[loading,setLoading]=useState(false);const[submitError,setSubmitError]=useState("");const total=Object.values(data).reduce((a,v)=>a+Number(v.count),0);const nav=useNavigate();async function submit(){setLoading(true);setSubmitError("");try{await submitWithDraft(zone,"social-cultural",{items:data,total,score:Math.min(10,total)},data,setStatus);setSubmitted(true);}catch(err){setSubmitError(submitErrorMessage(err,lang));}finally{setLoading(false);}}
  if(submitted)return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<h1 className="text-2xl font-black text-primary">{t("reviewTitle")}</h1><SubmittedBanner onBack={()=>nav(`/zone/${zone}?tab=tasks`, { replace: true })}/><div className="mt-4 space-y-3">{socialItems.map(k=><div className="field-card" key={k}><b>{t(k)}</b><p>{t("count")}: {data[k].count}</p><p className="text-sm text-muted-foreground">{data[k].description}</p></div>)}<div className="field-card"><b>{t("total")}: {total} · {t("score")}: {Math.min(10,total)}/10</b></div></div></Page>;
  return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<AutosaveBadge status={status}/><IndicatorCard text={t("socialIndicator")}/><div className="mt-4 space-y-3">{socialItems.map(k=><div className="field-card" key={k}><b>{t(k)}</b><input className="field-input mt-2 min-h-[44px]" type="number" min="0" value={data[k].count} onChange={e=>setData({...data,[k]:{...data[k],count:Number(e.target.value)}})} placeholder={t("count")}/><textarea className="field-input mt-2 min-h-24" value={data[k].description} onChange={e=>setData({...data,[k]:{...data[k],description:e.target.value}})} placeholder={t("description")}/></div>)}</div><div className="field-card mt-4"><b>{t("total")}: {total} · {t("score")}: {Math.min(10,total)}/10</b></div><SubmitErrorAlert message={submitError}/><SubmitBar onSubmit={submit} loading={loading}/></Page>;
}

export function EconomicForm(){
  const{t,lang}=useLanguage();const{zone}=useZoneTask();const isReview=useIsReview();const fallback=useMemo(()=>Object.fromEntries(goods.map(k=>[k,[0,0,0]])) as Record<string,number[]>,[]);const{data,setData,status,setStatus}=useDraftState(zone,"economic",fallback);const[submitted,setSubmitted]=useState(isReview);const[loading,setLoading]=useState(false);const[submitError,setSubmitError]=useState("");const avgs=goods.map(k=>{const valid=data[k].filter(n=>n>0);return valid.reduce((a,n)=>a+n,0)/(valid.length||1)});const zoneAvg=avgs.reduce((a,n)=>a+n,0)/3;const nav=useNavigate();async function submit(){setLoading(true);setSubmitError("");try{await submitWithDraft(zone,"economic",{prices:data,averages:avgs,zoneAverage:zoneAvg,index:moneyIndex(zoneAvg)},data,setStatus);setSubmitted(true);}catch(err){setSubmitError(submitErrorMessage(err,lang));}finally{setLoading(false);}}
  if(submitted)return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<h1 className="text-2xl font-black text-primary">{t("reviewTitle")}</h1><SubmittedBanner onBack={()=>nav(`/zone/${zone}?tab=tasks`, { replace: true })}/><div className="mt-4 space-y-3">{goods.map((k,gi)=><div className="field-card" key={k}><b>{t(k)}</b><div className="mt-2 grid grid-cols-3 gap-2">{data[k].map((v,i)=><div key={i} className="rounded-xl bg-muted p-2 text-center"><small>{t((`shop${i+1}`)as any)}</small><b className="block">{v?`$${v}`:"—"}</b></div>)}</div><p>{t("average")}: ${avgs[gi].toFixed(1)}</p></div>)}<div className="field-card"><b>{t("avgPrice")}: ${zoneAvg.toFixed(1)} · {t("affordability")}: {moneyIndex(zoneAvg)}/10</b></div></div></Page>;
  return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<AutosaveBadge status={status}/><IndicatorCard text={t("economicIndicator")}><div className="mt-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4">{[["$30–49","10"],["$50–89","7"],["$90–149","4"],[lang==="zh"?"$150以上":"$150+","1"]].map(([r,s])=><div className="rounded-xl bg-white p-2 text-center" key={s}><b>{r}</b><span className="block">{s} {t("points")}</span></div>)}</div></IndicatorCard><div className="mt-4 space-y-3">{goods.map(k=><div className="field-card" key={k}><b>{t(k)}</b><div className="mt-2 grid grid-cols-1 gap-2 sm:grid-cols-3">{[0,1,2].map(i=><input key={i} aria-label={`${t(k)} ${t((`shop${i+1}`)as any)}`} className="field-input min-h-[44px]" type="number" min="0" value={data[k][i]||""} onChange={e=>{const copy={...data,[k]:[...data[k]]};copy[k][i]=Number(e.target.value);setData(copy)}} placeholder={t((`shop${i+1}`)as any)}/>)}</div></div>)}</div><div className="field-card mt-4"><b>{t("avgPrice")}: ${zoneAvg.toFixed(1)} · {t("affordability")}: {moneyIndex(zoneAvg)}</b></div><SubmitErrorAlert message={submitError}/><SubmitBar onSubmit={submit} loading={loading}/></Page>;
}

export function ShopTallyForm(){
  const{t,lang}=useLanguage();const{zone}=useZoneTask();const isReview=useIsReview();const fallback=useMemo(()=>({counts:Object.fromEntries(shopTypes.map(k=>[k,0]))as Record<string,number>,grade:"midGrade"}),[]);const{data,setData,status,setStatus}=useDraftState(zone,"shop-tally",fallback);const[submitted,setSubmitted]=useState(isReview);const[loading,setLoading]=useState(false);const[submitError,setSubmitError]=useState("");const total=useMemo(()=>Object.values(data.counts).reduce((a,n)=>a+Number(n),0),[data]);const nav=useNavigate();async function submit(){setLoading(true);setSubmitError("");try{await submitWithDraft(zone,"shop-tally",{...data,total},data,setStatus);setSubmitted(true);}catch(err){setSubmitError(submitErrorMessage(err,lang));}finally{setLoading(false);}}
  if(submitted)return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<h1 className="text-2xl font-black text-primary">{t("reviewTitle")}</h1><SubmittedBanner onBack={()=>nav(`/zone/${zone}?tab=tasks`, { replace: true })}/><div className="mt-4 space-y-3">{shopTypes.map(k=><div className="field-card flex justify-between" key={k}><b>{t(k)}</b><span>{data.counts[k]} · {total?((data.counts[k]/total)*100).toFixed(1):0}%</span></div>)}<div className="field-card"><b>{t("total")}: {total} · {t("overallGrade")}: {t(data.grade as any)}</b></div></div></Page>;
  return <Page className="bg-cover bg-fixed bg-center" style={zoneBackgroundStyle(zone)}>{/* @section: task-form-zone-background */}<AutosaveBadge status={status}/><IndicatorCard text={t("shopIndicator")}/><div className="mt-4 space-y-3">{shopTypes.map(k=><label className="field-card block" key={k}><b>{t(k)}</b><input className="field-input mt-2 min-h-[44px]" type="number" min="0" value={data.counts[k]} onChange={e=>setData({...data,counts:{...data.counts,[k]:Number(e.target.value)}})}/><p className="text-sm text-muted-foreground">{t("percentage")}: {total?((data.counts[k]/total)*100).toFixed(1):0}%</p></label>)}</div><label className="mt-4 block font-semibold">{t("overallGrade")}<select className="field-input mt-2 min-h-[44px]" value={data.grade} onChange={e=>setData({...data,grade:e.target.value})}>{["highGrade","midGrade","lowGrade"].map(k=><option key={k} value={k}>{t(k as any)}</option>)}</select></label><SubmitErrorAlert message={submitError}/><SubmitBar onSubmit={submit} loading={loading}/></Page>;
}

export default function TaskRouter(){const{task}=useZoneTask();if(task==="environment")return <EnvironmentForm/>;if(task==="social-cultural")return <SocialCulturalForm/>;if(task==="economic")return <EconomicForm/>;if(task==="shop-tally")return <ShopTallyForm/>;return <BuildingScoringForm/>;}
