export type Lang = "zh" | "en";

export const translations = {
  zh: {
    appTitle: "灣仔再生", subtitle: "市區更新考察", school: "明愛陳震夏郊野學園", schoolEn: "Caritas Chan Chun Ha Field Studies Centre",
    login: "登入", enterName: "輸入姓名", groupNumber: "組別", memberNumber: "成員", fixedIdentityHint: "選擇固定組別及成員身份；資料會綁定此身份並在再次登入後恢復。", loadingData: "載入雲端資料…", loginFailed: "登入失敗，請重試。", startFieldwork: "開始考察", teacherLogin: "教師登入", studentLogin: "學生登入", username: "用戶名稱", password: "密碼", logout: "登出",
    locating: "定位中…", currentZone: "目前街區", gpsUnavailable: "GPS 未能定位，可手動進入街區", locked: "未解鎖", current: "目前", completed: "已完成", manualOpen: "手動進入", openZone: "進入街區", open: "開啟", nearZonePrefix: "你似乎接近街區", checkingNearbyZone: "正在檢查附近街區…", chooseAnyZone: "GPS 未能定位—請在下方選擇街區",
    zoneA: "街區 A：星街／莊士敦道西", zoneB: "街區 B：利東街一帶", zoneC: "街區 C：莊士敦道東／灣仔街市", zoneD: "街區 D：石水渠街／藍屋",
    map: "地圖", tasks: "任務", info: "地標資訊", photos: "拍攝", collectedData: "已收集數據", dataTableIntro: "此頁顯示此固定身份已儲存在伺服器的最新數據；可按街區及任務篩選，並修改已提交資料。", filterTask: "任務類型", allTasks: "全部任務", submittedAt: "提交時間", dataDetails: "數據內容", noFilteredData: "沒有符合篩選條件的數據。", refresh: "重新載入", amendData: "修改資料", updateSubmission: "更新提交", buildingScoring: "住宅樓宇外觀評分", environmental: "環境可持續性評估", socialCultural: "社會文化調查", economic: "社會經濟可持續性", shopTally: "地舖格調統計", photoTasks: "拍攝考察證據",
    submit: "提交", save: "儲存", next: "下一步", back: "返回", complete: "完成", total: "總分", average: "平均", grade: "級別", building: "樓宇", score: "分數", count: "數量", description: "描述／名稱", percentage: "百分比", overallGrade: "整體檔次", scoringIndicators: "評分指標", worksheetInstruction: "工作紙指示", points: "分",
    design: "樓宇設計", height: "樓宇高度", exterior: "外牆", windows: "窗戶", ac: "冷氣安裝位置", illegal: "僭建物及危險結構", entrance: "樓宇出入口",
    air: "空氣質素 PM2.5/10", noise: "噪音水平", hw: "高寬比", wind: "風流通潛力", green: "綠化覆蓋水平", cleanliness: "街道衛生情況",
    education: "教育設施", medical: "醫療及保健設施", arts: "藝術場地", publicSpace: "公共空間及社會福利設施", historic: "歷史性建築物",
    bread: "麵包（一排方包）", lunch: "午餐價錢", haircut: "髮型服務", shop1: "店舖一", shop2: "店舖二", shop3: "店舖三", avgPrice: "平均售價", affordability: "生活可負擔指數",
    fashionable: "時尚／具個性", chain: "連鎖店", traditional: "樸實／傳統", vacant: "空置", highGrade: "較高檔次", midGrade: "中等檔次", lowGrade: "較低檔次",
    severe: "嚴重衰落", poor: "欠佳", good: "良好", excellent: "極佳", high: "高", medium: "中等", low: "低", veryLow: "非常低", large: "大量", moderate: "一般", little: "少量", none: "無",
    guide: "操作動畫指引", hLine: "樓宇高度 H", wLine: "道路寬度 W", windGuide: "觀察建築物間風道、開揚度及街谷阻隔。", greenGuide: "估算視野內樹木、花槽及綠化平台覆蓋。", buildingGuide: "每區選五座具代表性的住宅，只觀察面向大街的正面，再按七項準則評分。",
    socialIndicator: "沿途找出教育、醫療保健（包括獸醫）、藝術場地、公共空間／社會福利設施及歷史建築；記錄數量及名稱，總數最高計10分。", economicIndicator: "每區調查三項主要民用商品；每項盡量記錄三間不同商店的代表性平均售價。沒有該商品可留空。區內平均售價愈低，可負擔指數愈高。", shopIndicator: "統計具代表性的地舖：時尚／具個性、連鎖、樸實／傳統及空置，計算百分比，並判斷主要貨品／服務屬較高、中等或較低檔次。",
    photo1: "街區建築風格", photo2: "店舖類型及格調", photo3: "社區設施", photo4: "具歷史價值建築物", photo5: "街道衛生及環境", cameraHint: "安全情況下拍攝，避免阻礙途人或店舖運作。",
    dashboard: "教師儀表板", totalGroups: "學生／小組", zonesCompleted: "已完成街區", submissionsToday: "今日提交", studentName: "學生身份", lastActive: "最後活動", submissions: "提交紀錄", viewData: "查看資料", noData: "暫無資料", syncOk: "已儲存並提交", syncLocal: "已先儲存在本機，稍後可再提交", required: "請填寫所需資料",
    takePhoto: "拍照／選擇圖片", uploadPhoto: "上傳", photoUploading: "上傳中…", photoUploaded: "已上傳", photoGallery: "相片集", allZones: "全部街區", allGroups: "全部小組", filterZone: "街區", filterGroup: "小組",
    reviewTitle: "提交確認", submittedBanner: "✓ 已成功提交", reviewBuildings: "樓宇評分", reviewEnvironment: "環境評估", reviewSocial: "社會文化", reviewEconomic: "社會經濟", reviewShop: "地舖統計", buildingAvg: "平均分", autosaveIdle: "尚未建立本機草稿 / No local draft yet", autosaveSaving: "正在自動儲存草稿… / Autosaving draft…", autosaveSaved: "草稿已儲存在本機 / Draft saved locally", autosaveRestored: "已恢復本機草稿 / Local draft restored", autosavePending: "提交未成功；草稿已保留，請稍後重試 / Submit failed; draft kept for retry", autosaveError: "本機草稿儲存失敗，但仍可嘗試提交 / Local draft save failed; server submit can still be tried", completionMatrix: "完成矩陣", taskLegend: "任務格編號",  allStudents: "全部學生", exportCsv: "匯出CSV", revisionHistory: "修訂歷史", viewHistory: "查看歷史", hideHistory: "隱藏歷史", revision: "版本", deleteEntry: "刪除紀錄"
  },
  en: {
    appTitle: "Reshaping Wan Chai", subtitle: "Urban Renewal Fieldwork", school: "明愛陳震夏郊野學園", schoolEn: "Caritas Chan Chun Ha Field Studies Centre",
    login: "Login", enterName: "Enter name", groupNumber: "Group", memberNumber: "Member", fixedIdentityHint: "Choose a fixed group and member identity. Data is tied to this identity and restored after the next login.", loadingData: "Loading saved data…", loginFailed: "Login failed. Please try again.", startFieldwork: "Start Fieldwork", teacherLogin: "Teacher login", studentLogin: "Student login", username: "Username", password: "Password", logout: "Log out",
    locating: "Locating…", currentZone: "Current zone", gpsUnavailable: "GPS unavailable. Manual zone entry is enabled.", locked: "Locked", current: "Current", completed: "Completed", manualOpen: "Manual entry", openZone: "Open zone", open: "Open", nearZonePrefix: "You appear to be near Zone", checkingNearbyZone: "Checking nearby zone…", chooseAnyZone: "GPS unavailable — choose any zone below",
    zoneA: "Zone A: Star Street / Johnston Rd West", zoneB: "Zone B: Lee Tung Avenue area", zoneC: "Zone C: Johnston Rd East / Wan Chai Market", zoneD: "Zone D: Stone Nullah Lane / Blue House",
    map: "Map", tasks: "Tasks", info: "Landmarks", photos: "Photos", collectedData: "Collected Data", dataTableIntro: "This page shows the latest server-saved data for this fixed identity. Filter by zone and task, or amend a submitted entry.", filterTask: "Task type", allTasks: "All tasks", submittedAt: "Submitted", dataDetails: "Data", noFilteredData: "No data matches these filters.", refresh: "Reload", amendData: "Amend data", updateSubmission: "Update submission", buildingScoring: "Building Scoring", environmental: "Environmental Assessment", socialCultural: "Social-Cultural Survey", economic: "Economic Sustainability", shopTally: "Shop Style", photoTasks: "Photo Tasks",
    submit: "Submit", save: "Save", next: "Next", back: "Back", complete: "Complete", total: "Total", average: "Average", grade: "Grade", building: "Building", score: "Score", count: "Count", description: "Description / name", percentage: "Percentage", overallGrade: "Overall grade", scoringIndicators: "Scoring Indicators", worksheetInstruction: "Worksheet instruction", points: "points",
    design: "Design", height: "Height", exterior: "Exterior Wall", windows: "Windows", ac: "AC Position", illegal: "Illegal Structures", entrance: "Entrance",
    air: "Air quality PM2.5/10", noise: "Noise level", hw: "H:W ratio", wind: "Wind ventilation", green: "Green cover", cleanliness: "Street cleanliness",
    education: "Education", medical: "Medical / Health", arts: "Arts venues", publicSpace: "Public space / welfare", historic: "Historic buildings",
    bread: "Bread loaf", lunch: "Lunch set", haircut: "Haircut", shop1: "Shop 1", shop2: "Shop 2", shop3: "Shop 3", avgPrice: "Average price", affordability: "Affordability index",
    fashionable: "Fashionable / Unique", chain: "Chain", traditional: "Traditional", vacant: "Vacant", highGrade: "Higher grade", midGrade: "Medium grade", lowGrade: "Lower grade",
    severe: "Severe decline", poor: "Poor", good: "Good", excellent: "Excellent", high: "High", medium: "Medium", low: "Low", veryLow: "Very low", large: "Large", moderate: "Moderate", little: "Little", none: "None",
    guide: "Animated task guide", hLine: "Building height H", wLine: "Road width W", windGuide: "Observe wind corridors, openness and street-canyon blockage.", greenGuide: "Estimate trees, planters and podium greenery in view.", buildingGuide: "In each zone choose five representative residential buildings. Observe only the façade facing the main street, then score all seven criteria.",
    socialIndicator: "Along the route, identify education, medical/health (including veterinary), arts, public space/social welfare and historic-building facilities. Record counts and names; the total score is capped at 10.", economicIndicator: "In each zone survey three essential goods. For each item, try to record a representative average price from three different shops. Leave it blank if unavailable. A lower zone average means a higher affordability score.", shopIndicator: "Tally representative ground-floor shops as fashionable/unique, chain, traditional or vacant; calculate percentages and judge the main goods/services as higher, medium or lower grade.",
    photo1: "Street building style", photo2: "Shop type and grade", photo3: "Community facilities", photo4: "Historic building", photo5: "Street hygiene and environment", cameraHint: "Take photos safely without blocking pedestrians or shops.",
    dashboard: "Teacher Dashboard", totalGroups: "Students / groups", zonesCompleted: "Zones completed", submissionsToday: "Submissions today", studentName: "Student identity", lastActive: "Last active", submissions: "Submissions", viewData: "View data", noData: "No data yet", syncOk: "Saved and submitted", syncLocal: "Saved locally first; submit again later", required: "Please complete required fields",
    takePhoto: "Take / choose photo", uploadPhoto: "Upload", photoUploading: "Uploading…", photoUploaded: "Uploaded", photoGallery: "Photo gallery", allZones: "All zones", allGroups: "All groups", filterZone: "Zone", filterGroup: "Group",
    reviewTitle: "Submission Review", submittedBanner: "✓ Submitted successfully", reviewBuildings: "Building scores", reviewEnvironment: "Environment", reviewSocial: "Social-Cultural", reviewEconomic: "Economic", reviewShop: "Shop tally", buildingAvg: "Average score", autosaveIdle: "No local draft yet / 尚未建立本機草稿", autosaveSaving: "Autosaving draft… / 正在自動儲存草稿…", autosaveSaved: "Draft saved locally / 草稿已儲存在本機", autosaveRestored: "Local draft restored / 已恢復本機草稿", autosavePending: "Submit failed; draft kept for retry / 提交未成功；草稿已保留，請稍後重試", autosaveError: "Local draft save failed; server submit can still be tried / 本機草稿儲存失敗，但仍可嘗試提交", completionMatrix: "Completion matrix", taskLegend: "Task cell legend",  allStudents: "All students", exportCsv: "Export CSV", revisionHistory: "Revision history", viewHistory: "View history", hideHistory: "Hide history", revision: "Revision", deleteEntry: "Delete entry"
  }
} as const;
export type TranslationKey = keyof typeof translations.en;
