import { useState } from "react";
import { ResponsiveContainer, BarChart, Bar, CartesianGrid, XAxis, YAxis, Tooltip, Legend, PieChart, Pie, Cell, RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ScatterChart, Scatter } from "recharts";
import { buildAnalysis } from "@/lib/analysisSummary";
import type { FieldworkSubmission } from "@/lib/fieldworkApi";
const colors = ["#94132b", "#137e8d", "#bb720a", "#6254a4"];
const names = ["時尚店舖", "連鎖店舖", "傳統店舖", "空置店舖"];
const indicators = [["environment", "環境"], ["cultural", "社會文化"], ["economic", "社會經濟"]] as const;
export const analysisTabs = [["building", "樓宇評分"], ["sustainability", "可持續性"], ["shops", "店舖比例"], ["radar", "雷達比較"], ["relationship", "關係圖"], ["tables", "數據表格"]];
export default function AnalysisCharts({ records, tab }: { records: FieldworkSubmission[]; tab: string }) {
  const summary = buildAnalysis(records);
  const [zone, setZone] = useState("A");
  const [relationship, setRelationship] = useState<"environment" | "cultural" | "economic" | "total">("total");
  const selected = summary.find(s => s.zone === zone)!;
  const complete = summary.filter(s => s.total !== null);
  const points = summary.filter(s => s.building !== null && s[relationship] !== null);
  const shopTotal = selected.shops.reduce((sum, s) => sum + (s.value ?? 0),0);
  const shopData = selected.shops.map((s,i) => ({ name: names[i], value: s.value ?? 0 }));
  return <section className="field-card mb-5">
    {tab === "building" && <><h2 className="text-xl font-bold text-primary">住宅樓宇外觀評分</h2><p className="my-3 text-sm">各街區已填組別的平均分，對應 Sheet「Part 1 Building」。</p><ResponsiveContainer width="100%" height={360}><BarChart data={summary}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="zone"/><YAxis/><Tooltip/><Bar dataKey="building" name="平均分" fill={colors[0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></>}
    {tab === "sustainability" && <><h2 className="text-xl font-bold text-primary">城市可持續發展程度</h2><p className="my-3 text-sm">對應 Sheet 摘要的堆疊橫條圖。每項為已填組別平均，三項相加為總分；只繪出三項齊全的街區。</p><ResponsiveContainer width="100%" height={360}><BarChart data={complete} layout="vertical" stackOffset="sign"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number"/><YAxis type="category" dataKey="zone"/><Tooltip/><Legend/>{indicators.map(([key,label],i) => <Bar key={key} dataKey={key} name={label} stackId="score" fill={colors[i]} isAnimationActive={false}/>)}</BarChart></ResponsiveContainer></>}
    {tab === "shops" && <><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold text-primary">地舖格調比例</h2><label>街區 <select value={zone} onChange={e => setZone(e.target.value)} className="field-input">{summary.map(s => <option key={s.zone}>{s.zone}</option>)}</select></label></div><p className="my-3 text-sm">各類店舖先加總各組數量，再除以店舖總數，對應 Sheet 圓形圖。</p>{shopTotal > 0 ? <ResponsiveContainer width="100%" height={360}><PieChart><Pie data={shopData} dataKey="value" nameKey="name" outerRadius={110} label={({ percent }) => `${((percent ?? 0)*100).toFixed(1)}%`} isAnimationActive={false}>{shopData.map((s,i) => <Cell key={s.name} fill={colors[i]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer> : <p className="py-16 text-center">未有可繪製比例的店舖數據（未填或總數為 0）。</p>}<div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{selected.shops.map((s,i) => <p key={s.key}>{names[i]}：{s.value ?? "—"}</p>)}</div></>}
    {tab === "radar" && <><h2 className="text-xl font-bold text-primary">各街區可持續性比較</h2><p className="my-3 text-sm">依摘要表的三項平均分繪製，保留原始分數、不作百分比標準化；只包含三項齊全的街區。</p><ResponsiveContainer width="100%" height={400}><RadarChart data={indicators.map(([key,label]) => ({ indicator: label, ...Object.fromEntries(complete.map(s => [s.zone,s[key]])) }))}><PolarGrid/><PolarAngleAxis dataKey="indicator"/><PolarRadiusAxis/><Tooltip/><Legend/>{complete.map(s => <Radar key={s.zone} dataKey={s.zone} name={`街區 ${s.zone}`} stroke={colors[summary.indexOf(s)]} fill={colors[summary.indexOf(s)]} fillOpacity={0.08} isAnimationActive={false}/>)}</RadarChart></ResponsiveContainer></>}
    {tab === "relationship" && <><h2 className="text-xl font-bold text-primary">市區更新與可持續性的關係</h2><label className="my-3 block">縱軸指標 <select className="field-input" value={relationship} onChange={e => setRelationship(e.target.value as typeof relationship)}><option value="total">三項總分</option>{indicators.map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label><p className="my-3 text-sm">橫軸：樓宇外觀平均分（參考表的市區更新指標）。每點為一個街區；兩項數值齊全才繪出，不代表因果關係。</p><ResponsiveContainer width="100%" height={360}><ScatterChart margin={{bottom:25,right:20,left:10,top:15}}><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" dataKey="building" name="樓宇外觀平均分" label={{value:"樓宇外觀平均分",position:"bottom"}}/><YAxis type="number" dataKey={relationship} name="可持續性分數"/><Tooltip cursor={{strokeDasharray:"3 3"}}/><Legend/>{points.map(s => <Scatter key={s.zone} name={`街區 ${s.zone}`} data={[s]} fill={colors[summary.indexOf(s)]} isAnimationActive={false}/>)}</ScatterChart></ResponsiveContainer></>}
    {(tab === "radar" || tab === "sustainability") && complete.length < 4 && <p className="text-sm text-amber-800">尚缺完整三項數據：{summary.filter(s => s.total === null).map(s => s.zone).join("、")}</p>}
    {tab === "relationship" && points.length === 0 && <p className="text-sm text-amber-800">目前沒有兩項數值齊全的街區。</p>}
    {tab !== "shops" && <details className="mt-4"><summary className="cursor-pointer font-semibold">查看圖表數值</summary><div className="overflow-x-auto"><table className="mt-3 w-full min-w-[550px] text-sm"><thead><tr>{["街區","樓宇","環境","社會文化","社會經濟","三項總分"].map(n => <th key={n} className="p-2">{n}</th>)}</tr></thead><tbody>{summary.map(s => <tr key={s.zone} className="border-t">{[s.zone,s.building,s.environment,s.cultural,s.economic,s.total].map((n,i) => <td key={i} className="p-2 text-center">{typeof n === "number" ? n.toFixed(2) : n ?? "—"}</td>)}</tr>)}</tbody></table></div></details>}
  </section>;
}
