import { Navigate, Link } from "react-router-dom";
import { useLanguage } from "@/i18n/LanguageContext";
import { getRole, hasToken, identityLabel, logout, type Role } from "@/lib/fieldworkApi";
import type { CSSProperties, ReactNode } from "react";

export function SchoolLogo({ className = "" }: { className?: string }) { return <img src="images/branding/school-logo.png" alt="Caritas Chan Chun Ha Field Studies Centre" className={`h-auto w-full object-contain ${className}`} />; }
export function Header() { const { t, lang, toggleLang } = useLanguage(); const identity = identityLabel(lang); return <header className="sticky top-0 z-10 border-b bg-primary shadow-md backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between gap-2 px-2 py-2 sm:gap-3 sm:px-3"><Link to="/map" className="flex min-w-0 flex-1 items-center"><span className="rounded-xl bg-white/95 px-2 py-1 shadow-sm ring-1 ring-white/40"><SchoolLogo className="max-h-7 max-w-[145px] sm:max-h-9 sm:max-w-[260px]" /></span><span className="sr-only">{lang === "zh" ? t("school") : t("schoolEn")} · {t("subtitle")}</span></Link><div className="flex flex-shrink-0 items-center gap-1 sm:gap-2">{identity && <span className="hidden rounded-xl bg-white/15 px-3 py-2 text-xs font-bold text-white sm:block">{identity}</span>}{hasToken() && getRole() === "student" && <Link to="/data" className="inline-flex min-h-[44px] items-center whitespace-nowrap rounded-xl border border-white/40 bg-white/10 px-2 py-2 text-xs font-semibold text-white hover:bg-white/20 sm:px-3 sm:text-sm">{t("collectedData")}</Link>}<button className="min-h-[44px] whitespace-nowrap rounded-xl border border-white/40 bg-white/10 px-2 py-2 text-sm font-semibold text-white hover:bg-white/20 sm:px-3" onClick={toggleLang}>{lang === "zh" ? "EN" : "中"}</button>{hasToken() && <button className="min-h-[44px] whitespace-nowrap rounded-xl border border-white/40 bg-white/10 px-2 py-2 text-sm font-semibold text-white hover:bg-white/20 sm:px-3" onClick={() => { logout(); location.href = `${location.pathname}${location.search}#/`; }}>{t("logout")}</button>}</div></div>{identity && <div className="border-t border-white/15 px-3 py-1 text-center text-xs font-bold text-white sm:hidden">{identity}</div>}</header>; }
export function Page({ children, className = "", style }: { children: ReactNode; className?: string; style?: CSSProperties }) { const mergedStyle: CSSProperties = { backgroundImage: "linear-gradient(rgba(248,250,247,.38), rgba(248,250,247,.48)), url('images/zone-c-background_2.png')", backgroundSize: "cover", backgroundPosition: "center", backgroundAttachment: "fixed", ...style }; return <div className={`app-shell text-slate-950 ${className}`} style={mergedStyle}><Header/><main className="mx-auto max-w-5xl p-4 pb-24 md:pb-6">{children}</main></div>; }
export function Protected({ role, children }: { role: Role; children: ReactNode }) { if (!hasToken() || getRole() !== role) return <Navigate to={role === "teacher" ? "/teacher-login" : "/"} replace />; return <>{children}</>; }
